### ISSUE TITLE
Remove print statement for unsupported format for files with no extension

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-variables#8]
When a file is passed without a file extension we print a message stating that we didn't find a suitable parser, and then assume the format is JSON. This happens in [Jenkins](http://jenkins-ci.org/) using the [Config File Provider plugin](https://wiki.jenkins-ci.org/display/JENKINS/Config+File+Provider+Plugin), which by default creates a temporary file without an extension. As no file extension is provided, we'd never find a suitable parser, so it's safe to simply assume it's JSON and avoid this message.

The relevant code is [here](https://github.com/davehunt/pytest-variables/blob/e2c1c97f394d0440ed87df85e0dcbec4f36c4318/pytest_variables.py#L51-L53) and this change should be accompanied with at least one test.

**Comment by RibeiroAna** [comment]
Just wrote a solution as an application contribution to Outreachy :)
